import { createSlice } from '@reduxjs/toolkit'

import { fetchJournal } from './journalAsync'

const journalSlice = createSlice({
  name          : 'journal',
  initialState  : {
    journal : [
      { section: 'January' },
      {
        id           : '605142d9fc13ae7757000000',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Padriac',
        audit_by     : 'Fields',
        cash_in_hand : '$0.16',
        expenses     : '$9.96',
        incomes      : '$7.85',
      },
      {
        id           : '605142d9fc13ae7757000001',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Lind',
        audit_by     : 'Devy',
        cash_in_hand : '$3.87',
        expenses     : '$9.14',
        incomes      : '$3.33',
      },
      {
        id           : '605142d9fc13ae7757000002',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Gwen',
        audit_by     : 'Lise',
        cash_in_hand : '$0.93',
        expenses     : '$3.85',
        incomes      : '$4.11',
      },
      {
        id           : '605142d9fc13ae7757000003',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Giacinta',
        audit_by     : 'Duffy',
        cash_in_hand : '$3.97',
        expenses     : '$5.19',
        incomes      : '$6.12',
      },
      {
        id           : '605142d9fc13ae7757000004',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Kirby',
        audit_by     : 'Lana',
        cash_in_hand : '$4.90',
        expenses     : '$7.73',
        incomes      : '$8.89',
      },
      {
        id           : '605142d9fc13ae7757000005',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Dre',
        audit_by     : 'Nicolai',
        cash_in_hand : '$0.63',
        expenses     : '$7.43',
        incomes      : '$7.90',
      },
      {
        id           : '605142d9fc13ae7757000006',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Beatriz',
        audit_by     : 'Florian',
        cash_in_hand : '$0.51',
        expenses     : '$0.37',
        incomes      : '$1.88',
      },
      {
        id           : '605142d9fc13ae7757000007',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Christina',
        audit_by     : 'Ray',
        cash_in_hand : '$0.48',
        expenses     : '$6.80',
        incomes      : '$7.27',
      },
      {
        id           : '605142d9fc13ae7757000008',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Lorrin',
        audit_by     : 'Rockwell',
        cash_in_hand : '$6.03',
        expenses     : '$7.05',
        incomes      : '$7.54',
      },
      {
        id           : '605142d9fc13ae7757000009',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Muire',
        audit_by     : 'Nananne',
        cash_in_hand : '$3.49',
        expenses     : '$3.73',
        incomes      : '$2.20',
      },
      {
        id           : '605142d9fc13ae775700000a',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Heinrik',
        audit_by     : 'Kincaid',
        cash_in_hand : '$9.71',
        expenses     : '$3.21',
        incomes      : '$6.47',
      },
      {
        id           : '605142d9fc13ae775700000b',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Jerald',
        audit_by     : 'Genvieve',
        cash_in_hand : '$1.07',
        expenses     : '$0.05',
        incomes      : '$6.50',
      },
      { section: 'February' },
      {
        id           : '605142d9fc13ae775700000c',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Tilly',
        audit_by     : 'Carmelina',
        cash_in_hand : '$4.87',
        expenses     : '$4.73',
        incomes      : '$3.25',
      },
      {
        id           : '605142d9fc13ae775700000d',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Jessey',
        audit_by     : 'Jasmin',
        cash_in_hand : '$0.27',
        expenses     : '$0.20',
        incomes      : '$5.75',
      },
      {
        id           : '605142d9fc13ae775700000e',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Jammie',
        audit_by     : 'Pam',
        cash_in_hand : '$5.82',
        expenses     : '$0.03',
        incomes      : '$5.23',
      },
      {
        id           : '605142d9fc13ae775700000f',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Yettie',
        audit_by     : 'Janos',
        cash_in_hand : '$1.04',
        expenses     : '$0.69',
        incomes      : '$3.45',
      },
      {
        id           : '605142d9fc13ae7757000010',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Odilia',
        audit_by     : 'Aggy',
        cash_in_hand : '$1.95',
        expenses     : '$3.18',
        incomes      : '$2.90',
      },
      {
        id           : '605142d9fc13ae7757000011',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Kerrie',
        audit_by     : 'Mariquilla',
        cash_in_hand : '$9.42',
        expenses     : '$3.60',
        incomes      : '$2.20',
      },
      {
        id           : '605142d9fc13ae7757000012',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Dorri',
        audit_by     : 'Gottfried',
        cash_in_hand : '$6.27',
        expenses     : '$8.17',
        incomes      : '$7.31',
      },
      {
        id           : '605142d9fc13ae7757000013',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Carlin',
        audit_by     : 'Darya',
        cash_in_hand : '$7.69',
        expenses     : '$9.42',
        incomes      : '$5.89',
      },
      {
        id           : '605142d9fc13ae7757000014',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Brett',
        audit_by     : 'Brendin',
        cash_in_hand : '$9.64',
        expenses     : '$6.07',
        incomes      : '$2.69',
      },
      {
        id           : '605142d9fc13ae7757000015',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Andrei',
        audit_by     : 'Lynnell',
        cash_in_hand : '$5.25',
        expenses     : '$1.75',
        incomes      : '$7.00',
      },
      { section: 'March' },
      {
        id           : '605142d9fc13ae7757000016',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Palm',
        audit_by     : 'Karie',
        cash_in_hand : '$9.76',
        expenses     : '$8.60',
        incomes      : '$0.04',
      },
      {
        id           : '605142d9fc13ae7757000017',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Norina',
        audit_by     : 'Cobb',
        cash_in_hand : '$6.61',
        expenses     : '$6.65',
        incomes      : '$6.69',
      },
      {
        id           : '605142d9fc13ae7757000018',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Curtis',
        audit_by     : 'Chere',
        cash_in_hand : '$2.24',
        expenses     : '$7.06',
        incomes      : '$7.47',
      },
      {
        id           : '605142d9fc13ae7757000019',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Rena',
        audit_by     : 'Tabbatha',
        cash_in_hand : '$1.37',
        expenses     : '$9.36',
        incomes      : '$2.11',
      },
      {
        id           : '605142d9fc13ae775700001a',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Heddi',
        audit_by     : 'Renard',
        cash_in_hand : '$2.07',
        expenses     : '$1.61',
        incomes      : '$0.70',
      },
      {
        id           : '605142d9fc13ae775700001b',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Lucienne',
        audit_by     : 'Ginnifer',
        cash_in_hand : '$8.07',
        expenses     : '$3.84',
        incomes      : '$0.64',
      },
      {
        id           : '605142d9fc13ae775700001c',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Cate',
        audit_by     : 'Chrystel',
        cash_in_hand : '$1.60',
        expenses     : '$5.46',
        incomes      : '$6.62',
      },
      {
        id           : '605142d9fc13ae775700001d',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Hayyim',
        audit_by     : 'Zilvia',
        cash_in_hand : '$8.81',
        expenses     : '$0.69',
        incomes      : '$1.09',
      },
      {
        id           : '605142d9fc13ae775700001e',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Tonia',
        audit_by     : 'Wilmer',
        cash_in_hand : '$9.05',
        expenses     : '$1.24',
        incomes      : '$5.65',
      },
      {
        id           : '605142d9fc13ae775700001f',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Tome',
        audit_by     : 'Walliw',
        cash_in_hand : '$6.69',
        expenses     : '$8.73',
        incomes      : '$6.99',
      },
      {
        id           : '605142d9fc13ae7757000020',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Tootsie',
        audit_by     : 'Asia',
        cash_in_hand : '$9.42',
        expenses     : '$6.15',
        incomes      : '$3.66',
      },
      {
        id           : '605142d9fc13ae7757000021',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Courtney',
        audit_by     : 'Mark',
        cash_in_hand : '$5.68',
        expenses     : '$3.75',
        incomes      : '$2.77',
      },
      {
        id           : '605142d9fc13ae7757000022',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'April',
        audit_by     : 'Cedric',
        cash_in_hand : '$4.45',
        expenses     : '$0.29',
        incomes      : '$8.66',
      },
      {
        id           : '605142d9fc13ae7757000023',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Sawyer',
        audit_by     : 'Holmes',
        cash_in_hand : '$2.86',
        expenses     : '$0.51',
        incomes      : '$0.66',
      },
      {
        id           : '605142d9fc13ae7757000024',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Essie',
        audit_by     : 'Valentine',
        cash_in_hand : '$6.45',
        expenses     : '$8.50',
        incomes      : '$5.30',
      },
      {
        id           : '605142d9fc13ae7757000025',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Hernando',
        audit_by     : 'Tymon',
        cash_in_hand : '$6.24',
        expenses     : '$6.03',
        incomes      : '$0.02',
      },
      {
        id           : '605142d9fc13ae7757000026',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Nerta',
        audit_by     : 'Johann',
        cash_in_hand : '$0.53',
        expenses     : '$0.74',
        incomes      : '$0.83',
      },
      { section: 'April' },
      {
        id           : '605142d9fc13ae7757000027',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Haze',
        audit_by     : 'Doralynn',
        cash_in_hand : '$9.59',
        expenses     : '$5.00',
        incomes      : '$8.64',
      },
      {
        id           : '605142d9fc13ae7757000028',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Dawna',
        audit_by     : 'Jacquenette',
        cash_in_hand : '$8.18',
        expenses     : '$1.04',
        incomes      : '$9.45',
      },
      {
        id           : '605142d9fc13ae7757000029',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Felicio',
        audit_by     : 'Gillie',
        cash_in_hand : '$1.26',
        expenses     : '$6.28',
        incomes      : '$2.01',
      },
      {
        id           : '605142d9fc13ae775700002a',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Kristo',
        audit_by     : 'Theresita',
        cash_in_hand : '$2.66',
        expenses     : '$5.10',
        incomes      : '$4.92',
      },
      {
        id           : '605142d9fc13ae775700002b',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Joaquin',
        audit_by     : 'Brendis',
        cash_in_hand : '$7.22',
        expenses     : '$2.76',
        incomes      : '$4.86',
      },
      {
        id           : '605142d9fc13ae775700002c',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Winnie',
        audit_by     : 'Brittney',
        cash_in_hand : '$4.61',
        expenses     : '$7.21',
        incomes      : '$8.74',
      },
      {
        id           : '605142d9fc13ae775700002d',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Walden',
        audit_by     : 'Farrand',
        cash_in_hand : '$9.80',
        expenses     : '$1.55',
        incomes      : '$5.01',
      },
      {
        id           : '605142d9fc13ae775700002e',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Daniela',
        audit_by     : 'Euell',
        cash_in_hand : '$2.68',
        expenses     : '$9.71',
        incomes      : '$6.38',
      },
      {
        id           : '605142d9fc13ae775700002f',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Ian',
        audit_by     : 'Daisy',
        cash_in_hand : '$7.28',
        expenses     : '$7.13',
        incomes      : '$7.15',
      },
      {
        id           : '605142d9fc13ae7757000030',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Dana',
        audit_by     : 'Zachery',
        cash_in_hand : '$2.51',
        expenses     : '$8.43',
        incomes      : '$7.43',
      },
      {
        id           : '605142d9fc13ae7757000031',
        day          : '30',
        month        : 'JAN',
        year         : '2020',
        create_by    : 'Selma',
        audit_by     : 'Baily',
        cash_in_hand : '$2.83',
        expenses     : '$7.76',
        incomes      : '$8.46',
      },
    ],
    status  : '',
    error   : '',
  },
  extraReducers : {
    [fetchJournal.pending]: state => {
      state.status = 'loading'
    },
    [fetchJournal.rejected]: (state, { error }) => {
      state.status = 'failed'
      state.error = error.message
    },
    [fetchJournal.fulfilled]: (state, { payload }) => {
      state.journal = payload
      state.status = 'success'
    },
  },
  reducers      : {
    replace(state, { payload }) {
      state[payload.key].push(payload.data)
    },
    add(state, { payload }) {
      state[payload.key].push(payload.data)
    },
    modify(state, { payload }) {
      state[payload.key].push(payload.data)
    },
    remove(state, { payload }) {
      state[payload.key].push(payload.data)
    },
  },
})

export const state = ({ journal, status, error }) => ({
  journal,
  status,
  error,
})
export const { replace, add, modify, remove } = journalSlice.actions
export default journalSlice.reducer
